"""Constants for the FLEXT Plugin system.

Centralized constants following flext-core patterns for consistency
across the plugin ecosystem.


Copyright (c) 2025 FLEXT Team. All rights reserved.
SPDX-License-Identifier: MIT
"""

from __future__ import annotations

# Plugin System Configuration
DEFAULT_PLUGIN_TIMEOUT_SECONDS = 30
DEFAULT_DISCOVERY_TIMEOUT_SECONDS = 10
DEFAULT_HOT_RELOAD_INTERVAL_SECONDS = 2
MAX_PLUGIN_WORKERS = 10
MIN_PLUGIN_WORKERS = 1

# Plugin File Extensions
PYTHON_PLUGIN_EXTENSION = ".py"
YAML_CONFIG_EXTENSION = ".yml"
JSON_CONFIG_EXTENSION = ".json"
TOML_CONFIG_EXTENSION = ".toml"

# Plugin Directory Names
DEFAULT_PLUGIN_DIR = "plugins"
DEFAULT_CACHE_DIR = ".plugin_cache"
DEFAULT_CONFIG_DIR = "config"

# Plugin Validation
MIN_PLUGIN_NAME_LENGTH = 3
MAX_PLUGIN_NAME_LENGTH = 100
VALID_PLUGIN_NAME_PATTERN = r"^[a-zA-Z][a-zA-Z0-9_-]*$"

# Hot Reload Configuration
HOT_RELOAD_DEBOUNCE_MS = 500
HOT_RELOAD_MAX_RETRIES = 3

# Plugin Lifecycle States
PLUGIN_LIFECYCLE_STATES = {
    "UNKNOWN",
    "DISCOVERED",
    "LOADED",
    "ACTIVE",
    "INACTIVE",
    "LOADING",
    "ERROR",
    "DISABLED",
    "HEALTHY",
    "UNHEALTHY",
}

# Plugin Types
SINGER_PLUGIN_TYPES = {"TAP", "TARGET", "TRANSFORM"}
ARCHITECTURE_PLUGIN_TYPES = {"EXTENSION", "SERVICE", "MIDDLEWARE", "TRANSFORMER"}
INTEGRATION_PLUGIN_TYPES = {"API", "DATABASE", "NOTIFICATION", "AUTHENTICATION"}
UTILITY_PLUGIN_TYPES = {"UTILITY", "TOOL", "HANDLER", "PROCESSOR"}

# Error Messages
PLUGIN_NOT_FOUND_MSG = "Plugin '{plugin_name}' not found"
PLUGIN_ALREADY_EXISTS_MSG = "Plugin '{plugin_name}' already exists"
PLUGIN_LOAD_FAILED_MSG = "Failed to load plugin '{plugin_name}': {error}"
PLUGIN_INVALID_NAME_MSG = "Invalid plugin name '{plugin_name}'"

__all__ = [
    "ARCHITECTURE_PLUGIN_TYPES",
    "DEFAULT_CACHE_DIR",
    "DEFAULT_CONFIG_DIR",
    "DEFAULT_DISCOVERY_TIMEOUT_SECONDS",
    "DEFAULT_HOT_RELOAD_INTERVAL_SECONDS",
    "DEFAULT_PLUGIN_DIR",
    "DEFAULT_PLUGIN_TIMEOUT_SECONDS",
    "HOT_RELOAD_DEBOUNCE_MS",
    "HOT_RELOAD_MAX_RETRIES",
    "INTEGRATION_PLUGIN_TYPES",
    "JSON_CONFIG_EXTENSION",
    "MAX_PLUGIN_NAME_LENGTH",
    "MAX_PLUGIN_WORKERS",
    "MIN_PLUGIN_NAME_LENGTH",
    "MIN_PLUGIN_WORKERS",
    "PLUGIN_ALREADY_EXISTS_MSG",
    "PLUGIN_INVALID_NAME_MSG",
    "PLUGIN_LIFECYCLE_STATES",
    "PLUGIN_LOAD_FAILED_MSG",
    "PLUGIN_NOT_FOUND_MSG",
    "PYTHON_PLUGIN_EXTENSION",
    "SINGER_PLUGIN_TYPES",
    "TOML_CONFIG_EXTENSION",
    "UTILITY_PLUGIN_TYPES",
    "VALID_PLUGIN_NAME_PATTERN",
    "YAML_CONFIG_EXTENSION",
]
