"""FLEXT Plugin Protocols - Advanced protocol composition.

Copyright (c) 2025 FLEXT Team. All rights reserved.
SPDX-License-Identifier: MIT

"""

from __future__ import annotations

from typing import Protocol

from flext_core import FlextResult


class FlextPluginProtocols:
    """Advanced plugin protocols with composition patterns."""

    # Core plugin operations
    class PluginLoader(Protocol):
        async def load_plugin(
            self, plugin_path: str
        ) -> FlextResult[dict[str, object]]: ...
        async def unload_plugin(self, plugin_name: str) -> FlextResult[bool]: ...
        def is_plugin_loaded(self, plugin_name: str) -> bool: ...
        def get_loaded_plugins(self) -> list[str]: ...

    class PluginDiscovery(Protocol):
        async def discover_plugins(
            self, paths: list[str]
        ) -> FlextResult[list[dict[str, object]]]: ...
        async def discover_plugin(
            self, plugin_path: str
        ) -> FlextResult[dict[str, object]]: ...
        async def validate_plugin(
            self, plugin_data: dict[str, object]
        ) -> FlextResult[bool]: ...

    class PluginRegistry(Protocol):
        async def register_plugin(self, plugin: object) -> FlextResult[bool]: ...
        async def unregister_plugin(self, plugin_name: str) -> FlextResult[bool]: ...
        async def get_plugin(self, plugin_name: str) -> FlextResult[object | None]: ...
        async def list_plugins(self) -> FlextResult[list[dict[str, object]]]: ...
        def is_plugin_registered(self, plugin_name: str) -> bool: ...

    class PluginExecution(Protocol):
        async def execute_plugin(
            self, plugin_name: str, context: dict[str, object]
        ) -> FlextResult[dict[str, object]]: ...
        async def stop_execution(self, execution_id: str) -> FlextResult[bool]: ...
        async def get_execution_status(self, execution_id: str) -> FlextResult[str]: ...
        def list_running_executions(self) -> list[str]: ...

    # Advanced plugin features
    class PluginSecurity(Protocol):
        async def validate_plugin(self, plugin: object) -> FlextResult[bool]: ...
        async def check_permissions(
            self, plugin_name: str, permissions: list[str]
        ) -> FlextResult[bool]: ...
        async def scan_plugin_security(
            self, plugin_path: str
        ) -> FlextResult[dict[str, object]]: ...
        async def get_security_level(self, plugin_name: str) -> FlextResult[str]: ...

    class PluginHotReload(Protocol):
        def start_watching(self, paths: list[str]) -> FlextResult[bool]: ...
        def stop_watching(self) -> FlextResult[bool]: ...
        def reload_plugin(self, plugin_name: str) -> FlextResult[bool]: ...
        def is_watching(self) -> bool: ...
        def get_watched_paths(self) -> list[str]: ...

    class PluginMonitoring(Protocol):
        async def start_monitoring(self, plugin_name: str) -> FlextResult[bool]: ...
        async def stop_monitoring(self, plugin_name: str) -> FlextResult[bool]: ...
        async def get_plugin_metrics(
            self, plugin_name: str
        ) -> FlextResult[dict[str, object]]: ...
        async def get_plugin_health(
            self, plugin_name: str
        ) -> FlextResult[dict[str, object]]: ...
        def is_monitoring(self, plugin_name: str) -> bool: ...

    class PluginConfiguration(Protocol):
        def load_config(self, plugin_name: str) -> FlextResult[dict[str, object]]: ...
        def save_config(
            self, plugin_name: str, config: dict[str, object]
        ) -> FlextResult[bool]: ...
        def validate_config(self, config: dict[str, object]) -> FlextResult[bool]: ...
        def get_default_config(
            self, plugin_type: str
        ) -> FlextResult[dict[str, object]]: ...

    class PluginLifecycle(Protocol):
        def initialize_plugin(self, plugin_name: str) -> FlextResult[bool]: ...
        def activate_plugin(self, plugin_name: str) -> FlextResult[bool]: ...
        def deactivate_plugin(self, plugin_name: str) -> FlextResult[bool]: ...
        def destroy_plugin(self, plugin_name: str) -> FlextResult[bool]: ...
        def get_plugin_status(self, plugin_name: str) -> FlextResult[str]: ...
        def list_plugin_statuses(self) -> FlextResult[dict[str, str]]: ...

    class PluginValidation(Protocol):
        def validate_plugin_structure(
            self, plugin_data: dict[str, object]
        ) -> FlextResult[bool]: ...
        def validate_plugin_dependencies(
            self, plugin_name: str
        ) -> FlextResult[bool]: ...
        def validate_plugin_permissions(
            self, plugin_name: str
        ) -> FlextResult[bool]: ...
        def validate_plugin_compatibility(
            self, plugin_name: str
        ) -> FlextResult[bool]: ...

    class PluginStorage(Protocol):
        def store_plugin(self, plugin_data: dict[str, object]) -> FlextResult[bool]: ...
        def retrieve_plugin(
            self, plugin_name: str
        ) -> FlextResult[dict[str, object] | None]: ...
        def delete_plugin(self, plugin_name: str) -> FlextResult[bool]: ...
        def list_stored_plugins(self) -> FlextResult[list[str]]: ...
        def plugin_exists(self, plugin_name: str) -> bool: ...


__all__ = ["FlextPluginProtocols"]
